version: '3'

services:
   
    #PHP
    php:
        build: 
            context: .
            dockerfile: development/app.dockerfile
        container_name: php
        tty: true
        env_file: .env
        volumes: 
            - .:/var/www
        ports:
            - "9000:9000"
        networks: 
            - laravel         

    #NGINX
    nginx:
        image: nginx:alpine
        container_name: nginx
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./development/vhost.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - laravel

    #MYSQL
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: challenge
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql            
        networks: 
            - laravel
    
    #CACHE
    cache:
        container_name: cache
        tty: true
        image: redis:latest
        networks: 
            - laravel

#NETWORKS
networks: 
    laravel:
        driver: bridge

#VOLUMES
volumes:        
    dbdata:
        driver: local