version: '3'

networks: 
    laravel:

services:

  # The Web Server
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - .development/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel
   
  # The Database
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: challenge
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: development/app.dockerfile
        container_name: php
        volumes: 
            - .:/var/www
        ports:
            - "9000:9000"
        networks: 
            - laravel
    
    cache:
        image: redis:3.0-alpine